const BASE_API = ' https://yts.mx/api/v2/';

class API {
  async getSuggestion(id) {
    //const url = `${BASE_API}movie_suggestions.json?movie_id=${id}`;
    // const resp = await fetch(url)
    // console.log(resp.data)

    const movies = [
          {
            "id": 4985,
            "url": "https://yts.mx/movies/that-evening-sun-2009",
            "imdb_code": "tt1114680",
            "title": "That Evening Sun",
            "title_english": "That Evening Sun",
            "title_long": "That Evening Sun (2009)",
            "slug": "that-evening-sun-2009",
            "year": 2009,
            "rating": 7.1,
            "runtime": 109,
            "genres": [
              "Action",
              "Drama"
            ],
            "summary": "An aging farmer fights to keep the home that is rightfully his after fleeing from a nursing home and discovering that his son has leased the family farm to his old nemesis. Placed in a nursing home by his son and promptly forgotten, Abner Meecham (Hal Holbrook) realized that waiting to die was no way to live. Determined to enjoy his last days, Abner packed his bags and set his sights on the family farm. At least there he could die on his own land, in familiar surroundings. But Abner is in for a rude awakening, because upon returning home he discovers that his son has leased the farm to Lonzo Choat. Abner never cared much for Lonzo, and when Lonzo refuses to leave, Abner takes up residence in an old tenant shack on the property. Before long, their dispute becomes volatile, each man believing himself to be in the right, and refusing to back down from his position. Betrayed by his son and haunted by dreams of his beloved deceased wife, Abner draws a line in the sand in an attempt to ...",
            "description_full": "An aging farmer fights to keep the home that is rightfully his after fleeing from a nursing home and discovering that his son has leased the family farm to his old nemesis. Placed in a nursing home by his son and promptly forgotten, Abner Meecham (Hal Holbrook) realized that waiting to die was no way to live. Determined to enjoy his last days, Abner packed his bags and set his sights on the family farm. At least there he could die on his own land, in familiar surroundings. But Abner is in for a rude awakening, because upon returning home he discovers that his son has leased the farm to Lonzo Choat. Abner never cared much for Lonzo, and when Lonzo refuses to leave, Abner takes up residence in an old tenant shack on the property. Before long, their dispute becomes volatile, each man believing himself to be in the right, and refusing to back down from his position. Betrayed by his son and haunted by dreams of his beloved deceased wife, Abner draws a line in the sand in an attempt to ...",
            "synopsis": "An aging farmer fights to keep the home that is rightfully his after fleeing from a nursing home and discovering that his son has leased the family farm to his old nemesis. Placed in a nursing home by his son and promptly forgotten, Abner Meecham (Hal Holbrook) realized that waiting to die was no way to live. Determined to enjoy his last days, Abner packed his bags and set his sights on the family farm. At least there he could die on his own land, in familiar surroundings. But Abner is in for a rude awakening, because upon returning home he discovers that his son has leased the farm to Lonzo Choat. Abner never cared much for Lonzo, and when Lonzo refuses to leave, Abner takes up residence in an old tenant shack on the property. Before long, their dispute becomes volatile, each man believing himself to be in the right, and refusing to back down from his position. Betrayed by his son and haunted by dreams of his beloved deceased wife, Abner draws a line in the sand in an attempt to ...",
            "yt_trailer_code": "tq4KnreDMgQ",
            "language": "en",
            "mpa_rating": "PG-13",
            "background_image": "https://yts.mx/assets/images/movies/that_evening_sun_2009/background.jpg",
            "background_image_original": "https://yts.mx/assets/images/movies/that_evening_sun_2009/background.jpg",
            "small_cover_image": "https://yts.mx/assets/images/movies/that_evening_sun_2009/small-cover.jpg",
            "medium_cover_image": "https://yts.mx/assets/images/movies/that_evening_sun_2009/medium-cover.jpg",
            "state": "ok",
            "torrents": [
              {
                "url": "https://yts.mx/torrent/download/2EB9D32A1BA9EEC7037B4A8305DAAB8B33EC42AE",
                "hash": "2EB9D32A1BA9EEC7037B4A8305DAAB8B33EC42AE",
                "quality": "720p",
                "seeds": 4,
                "peers": 1,
                "size": "794.35 MB",
                "size_bytes": 832936346,
                "date_uploaded": "2016-01-24 15:08:55",
                "date_uploaded_unix": 1453644535
              },
              {
                "url": "https://yts.mx/torrent/download/2E1FE37CEBFF64FC87A93232EAC7DF16526F42D8",
                "hash": "2E1FE37CEBFF64FC87A93232EAC7DF16526F42D8",
                "quality": "1080p",
                "seeds": 0,
                "peers": 2,
                "size": "1.65 GB",
                "size_bytes": 1771674010,
                "date_uploaded": "2016-01-24 17:47:49",
                "date_uploaded_unix": 1453654069
              }
            ],
            "date_uploaded": "2016-01-24 15:08:55",
            "date_uploaded_unix": 1453644535
          },
          {
            "id": 6393,
            "url": "https://yts.mx/movies/colossus-the-forbin-project-1970",
            "imdb_code": "tt0064177",
            "title": "Colossus: The Forbin Project",
            "title_english": "Colossus: The Forbin Project",
            "title_long": "Colossus: The Forbin Project (1970)",
            "slug": "colossus-the-forbin-project-1970",
            "year": 1970,
            "rating": 7.1,
            "runtime": 100,
            "genres": [
              "Action",
              "Sci-Fi",
              "Thriller"
            ],
            "summary": "Forbin is the designer of an incredibly sophisticated computer that will run all of America's nuclear defenses. Shortly after being turned on, it detects the existence of Guardian, the Soviet counterpart, previously unknown to US Planners. Both computers insist that they be linked, and after taking safeguards to preserve confidential material, each side agrees to allow it. As soon as the link is established the two become a new Super computer and threaten the world with the immediate launch of nuclear weapons if they are detached. Colossus begins to give its plans for the management of the world under its guidance. Forbin and the other scientists form a technological resistance to Colossus which must operate underground.",
            "description_full": "Forbin is the designer of an incredibly sophisticated computer that will run all of America's nuclear defenses. Shortly after being turned on, it detects the existence of Guardian, the Soviet counterpart, previously unknown to US Planners. Both computers insist that they be linked, and after taking safeguards to preserve confidential material, each side agrees to allow it. As soon as the link is established the two become a new Super computer and threaten the world with the immediate launch of nuclear weapons if they are detached. Colossus begins to give its plans for the management of the world under its guidance. Forbin and the other scientists form a technological resistance to Colossus which must operate underground.",
            "synopsis": "Forbin is the designer of an incredibly sophisticated computer that will run all of America's nuclear defenses. Shortly after being turned on, it detects the existence of Guardian, the Soviet counterpart, previously unknown to US Planners. Both computers insist that they be linked, and after taking safeguards to preserve confidential material, each side agrees to allow it. As soon as the link is established the two become a new Super computer and threaten the world with the immediate launch of nuclear weapons if they are detached. Colossus begins to give its plans for the management of the world under its guidance. Forbin and the other scientists form a technological resistance to Colossus which must operate underground.",
            "yt_trailer_code": "t46Kjy-IJpY",
            "language": "en",
            "mpa_rating": "",
            "background_image": "https://yts.mx/assets/images/movies/colossus_the_forbin_project_1970/background.jpg",
            "background_image_original": "https://yts.mx/assets/images/movies/colossus_the_forbin_project_1970/background.jpg",
            "small_cover_image": "https://yts.mx/assets/images/movies/colossus_the_forbin_project_1970/small-cover.jpg",
            "medium_cover_image": "https://yts.mx/assets/images/movies/colossus_the_forbin_project_1970/medium-cover.jpg",
            "state": "ok",
            "torrents": [
              {
                "url": "https://yts.mx/torrent/download/F80C8B3CE3F923A99074C630D25AC6021C062C74",
                "hash": "F80C8B3CE3F923A99074C630D25AC6021C062C74",
                "quality": "720p",
                "seeds": 3,
                "peers": 0,
                "size": "710.88 MB",
                "size_bytes": 745411707,
                "date_uploaded": "2017-03-28 20:13:30",
                "date_uploaded_unix": 1490724810
              },
              {
                "url": "https://yts.mx/torrent/download/69D516320D085987BA080F23465736073A2567B5",
                "hash": "69D516320D085987BA080F23465736073A2567B5",
                "quality": "1080p",
                "seeds": 11,
                "peers": 0,
                "size": "1.5 GB",
                "size_bytes": 1610612736,
                "date_uploaded": "2017-03-28 22:08:56",
                "date_uploaded_unix": 1490731736
              }
            ],
            "date_uploaded": "2017-03-28 20:13:30",
            "date_uploaded_unix": 1490724810
          },
          {
            "id": 4860,
            "url": "https://yts.mx/movies/the-blue-lagoon-1980",
            "imdb_code": "tt0080453",
            "title": "The Blue Lagoon",
            "title_english": "The Blue Lagoon",
            "title_long": "The Blue Lagoon (1980)",
            "slug": "the-blue-lagoon-1980",
            "year": 1980,
            "rating": 5.8,
            "runtime": 104,
            "genres": [
              "Action",
              "Adventure",
              "Drama",
              "Romance"
            ],
            "summary": "On a journey to San Francisco, Richard, his father and cousin Emmeline find themselves on a ship about to explode. Rushed to a lifeboat with Paddy Button, the two children escape while their father (and uncle) are on another lifeboat. In the chaos following, the lifeboats are separated. Paddy, Richard and Emmeline find themselves with no food and no water stuck in the middle of nowhere. After some time, the three come across an uncharted paradise, where Paddy quickly teaches the children fishing, hunting and building. After maybe a month or two, Paddy gets very drunk off a barrel of rum found on the island when they first arrive, and drowns in the middle of the night. Emmeline and Richard, now alone and very scared, move location and rebuild their island home. Many years later, the two young teenagers have developed a very real home, but hormones and feelings between the two strain their friendship, until Richard, who is still very determined to reach San Francisco, is let down by ...",
            "description_full": "On a journey to San Francisco, Richard, his father and cousin Emmeline find themselves on a ship about to explode. Rushed to a lifeboat with Paddy Button, the two children escape while their father (and uncle) are on another lifeboat. In the chaos following, the lifeboats are separated. Paddy, Richard and Emmeline find themselves with no food and no water stuck in the middle of nowhere. After some time, the three come across an uncharted paradise, where Paddy quickly teaches the children fishing, hunting and building. After maybe a month or two, Paddy gets very drunk off a barrel of rum found on the island when they first arrive, and drowns in the middle of the night. Emmeline and Richard, now alone and very scared, move location and rebuild their island home. Many years later, the two young teenagers have developed a very real home, but hormones and feelings between the two strain their friendship, until Richard, who is still very determined to reach San Francisco, is let down by ...",
            "synopsis": "On a journey to San Francisco, Richard, his father and cousin Emmeline find themselves on a ship about to explode. Rushed to a lifeboat with Paddy Button, the two children escape while their father (and uncle) are on another lifeboat. In the chaos following, the lifeboats are separated. Paddy, Richard and Emmeline find themselves with no food and no water stuck in the middle of nowhere. After some time, the three come across an uncharted paradise, where Paddy quickly teaches the children fishing, hunting and building. After maybe a month or two, Paddy gets very drunk off a barrel of rum found on the island when they first arrive, and drowns in the middle of the night. Emmeline and Richard, now alone and very scared, move location and rebuild their island home. Many years later, the two young teenagers have developed a very real home, but hormones and feelings between the two strain their friendship, until Richard, who is still very determined to reach San Francisco, is let down by ...",
            "yt_trailer_code": "1nC0EdXk_2g",
            "language": "en",
            "mpa_rating": "",
            "background_image": "https://yts.mx/assets/images/movies/the_blue_lagoon_1980/background.jpg",
            "background_image_original": "https://yts.mx/assets/images/movies/the_blue_lagoon_1980/background.jpg",
            "small_cover_image": "https://yts.mx/assets/images/movies/the_blue_lagoon_1980/small-cover.jpg",
            "medium_cover_image": "https://yts.mx/assets/images/movies/the_blue_lagoon_1980/medium-cover.jpg",
            "state": "ok",
            "torrents": [
              {
                "url": "https://yts.mx/torrent/download/DE019A30D2D51EF95F8674647CCD486A26CCC013",
                "hash": "DE019A30D2D51EF95F8674647CCD486A26CCC013",
                "quality": "720p",
                "seeds": 33,
                "peers": 18,
                "size": "775.59 MB",
                "size_bytes": 813265060,
                "date_uploaded": "2015-12-29 17:58:35",
                "date_uploaded_unix": 1451408315
              },
              {
                "url": "https://yts.mx/torrent/download/96528978B6AEF162D3C36F3D6C3A4FE9784F9BAB",
                "hash": "96528978B6AEF162D3C36F3D6C3A4FE9784F9BAB",
                "quality": "1080p",
                "seeds": 45,
                "peers": 16,
                "size": "1.6 GB",
                "size_bytes": 1717986918,
                "date_uploaded": "2015-12-29 17:58:38",
                "date_uploaded_unix": 1451408318
              }
            ],
            "date_uploaded": "2015-12-29 17:58:35",
            "date_uploaded_unix": 1451408315
          },
          {
            "id": 22114,
            "url": "https://yts.mx/movies/ben-10-vs-the-universe-the-movie-2020",
            "imdb_code": "tt13186528",
            "title": "Ben 10 vs. the Universe: The Movie",
            "title_english": "Ben 10 vs. the Universe: The Movie",
            "title_long": "Ben 10 vs. the Universe: The Movie (2020)",
            "slug": "ben-10-vs-the-universe-the-movie-2020",
            "year": 2020,
            "rating": 6.1,
            "runtime": 72,
            "genres": [
              "Action",
              "Adventure",
              "Animation"
            ],
            "summary": "A blast from Ben's past returns to do double the damage on Team Tennyson and planet Earth itself, forcing Ben to go interstellar to save the day.",
            "description_full": "A blast from Ben's past returns to do double the damage on Team Tennyson and planet Earth itself, forcing Ben to go interstellar to save the day.",
            "synopsis": "A blast from Ben's past returns to do double the damage on Team Tennyson and planet Earth itself, forcing Ben to go interstellar to save the day.",
            "yt_trailer_code": "opR_2-IBw8E",
            "language": "en",
            "mpa_rating": "",
            "background_image": "https://yts.mx/assets/images/movies/ben_10_vs_the_universe_the_movie_2020/background.jpg",
            "background_image_original": "https://yts.mx/assets/images/movies/ben_10_vs_the_universe_the_movie_2020/background.jpg",
            "small_cover_image": "https://yts.mx/assets/images/movies/ben_10_vs_the_universe_the_movie_2020/small-cover.jpg",
            "medium_cover_image": "https://yts.mx/assets/images/movies/ben_10_vs_the_universe_the_movie_2020/medium-cover.jpg",
            "state": "ok",
            "torrents": [
              {
                "url": "https://yts.mx/torrent/download/6197AFD841A13C253172F63A27D155571D20E8E1",
                "hash": "6197AFD841A13C253172F63A27D155571D20E8E1",
                "quality": "720p",
                "seeds": 508,
                "peers": 82,
                "size": "662.9 MB",
                "size_bytes": 695101030,
                "date_uploaded": "2020-10-11 09:44:32",
                "date_uploaded_unix": 1602402272
              },
              {
                "url": "https://yts.mx/torrent/download/11B2A09426608AAE6E2439B7ADF52CC1625ED83A",
                "hash": "11B2A09426608AAE6E2439B7ADF52CC1625ED83A",
                "quality": "1080p",
                "seeds": 429,
                "peers": 51,
                "size": "1.2 GB",
                "size_bytes": 1288490189,
                "date_uploaded": "2020-10-11 11:12:53",
                "date_uploaded_unix": 1602407573
              }
            ],
            "date_uploaded": "2020-10-11 09:44:32",
            "date_uploaded_unix": 1602402272
          }
        ]

    return movies;
  }

  async getMovies(){

    const categories = [
      {
        "id": 22556,
        "url": "https://yts.mx/movies/murmur-2019",
        "imdb_code": "tt10475900",
        "title": "Murmur",
        "title_english": "Murmur",
        "title_long": "Murmur (2019)",
        "slug": "murmur-2019",
        "year": 2019,
        "rating": 5.8,
        "runtime": 84,
        "genres": [
          "Drama"
        ],
        "summary": "Donna has recently been convicted of \"Driving While Impaired\" and is ordered to perform community service at the local animal shelter. When an elderly dog is scheduled to be euthanized, Donna decides to take the dog home and quickly realizes his companionship can ease her loneliness. To fill the emptiness she feels, Donna begins to take home more and more animals and she is soon in over her head.",
        "description_full": "Donna has recently been convicted of \"Driving While Impaired\" and is ordered to perform community service at the local animal shelter. When an elderly dog is scheduled to be euthanized, Donna decides to take the dog home and quickly realizes his companionship can ease her loneliness. To fill the emptiness she feels, Donna begins to take home more and more animals and she is soon in over her head.",
        "synopsis": "Donna has recently been convicted of \"Driving While Impaired\" and is ordered to perform community service at the local animal shelter. When an elderly dog is scheduled to be euthanized, Donna decides to take the dog home and quickly realizes his companionship can ease her loneliness. To fill the emptiness she feels, Donna begins to take home more and more animals and she is soon in over her head.",
        "yt_trailer_code": "h-RawDu8hY0",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/murmur_2019/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/murmur_2019/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/murmur_2019/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/murmur_2019/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/murmur_2019/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/5F27111F01214573F98ADDB9E3D4F0DAA2BC813C",
            "hash": "5F27111F01214573F98ADDB9E3D4F0DAA2BC813C",
            "quality": "720p",
            "type": "web",
            "seeds": 44,
            "peers": 19,
            "size": "789.89 MB",
            "size_bytes": 828259697,
            "date_uploaded": "2020-10-17 08:22:00",
            "date_uploaded_unix": 1602915720
          },
          {
            "url": "https://yts.mx/torrent/download/8CB0D17BCF096CBB0786D9AF634D92F74138D54C",
            "hash": "8CB0D17BCF096CBB0786D9AF634D92F74138D54C",
            "quality": "1080p",
            "type": "web",
            "seeds": 68,
            "peers": 19,
            "size": "1.59 GB",
            "size_bytes": 1707249500,
            "date_uploaded": "2020-10-17 09:43:45",
            "date_uploaded_unix": 1602920625
          }
        ],
        "date_uploaded": "2020-10-17 08:22:00",
        "date_uploaded_unix": 1602915720
      },
      {
        "id": 22548,
        "url": "https://yts.mx/movies/clouds-2020",
        "imdb_code": "tt6473066",
        "title": "Clouds",
        "title_english": "Clouds",
        "title_long": "Clouds (2020)",
        "slug": "clouds-2020",
        "year": 2020,
        "rating": 7.5,
        "runtime": 121,
        "genres": [
          "Drama",
          "Music"
        ],
        "summary": "Seventeen-year-old Zach Sobiech is a fun-loving high school senior with raw musical talent. But a few weeks into his senior year, just after asking out his long-time crush, Zach's world gets turned upside down when he finds out his cancer has spread, leaving him with a life expectancy of just six months. With the limited time he has left, he and his best friend and writing partner, Sammy, decide to follow their dreams and finally make an album. Little do they know, they'll soon become a viral music phenomenon. But with time running out, Zach is confronted with the reality that no matter how he spends his time, he is going to hurt the people he loves the most, including Amy, the love of his life. As Zach's health condition begins to worsen, he is left to make difficult decisions about how to spend his time and more importantly with whom. Ultimately, he discovers the best way to say goodbye is with music, and his hit song CLOUDS is born. With an unfiltered, heartbreaking, and beautiful ...",
        "description_full": "Seventeen-year-old Zach Sobiech is a fun-loving high school senior with raw musical talent. But a few weeks into his senior year, just after asking out his long-time crush, Zach's world gets turned upside down when he finds out his cancer has spread, leaving him with a life expectancy of just six months. With the limited time he has left, he and his best friend and writing partner, Sammy, decide to follow their dreams and finally make an album. Little do they know, they'll soon become a viral music phenomenon. But with time running out, Zach is confronted with the reality that no matter how he spends his time, he is going to hurt the people he loves the most, including Amy, the love of his life. As Zach's health condition begins to worsen, he is left to make difficult decisions about how to spend his time and more importantly with whom. Ultimately, he discovers the best way to say goodbye is with music, and his hit song CLOUDS is born. With an unfiltered, heartbreaking, and beautiful ...",
        "synopsis": "Seventeen-year-old Zach Sobiech is a fun-loving high school senior with raw musical talent. But a few weeks into his senior year, just after asking out his long-time crush, Zach's world gets turned upside down when he finds out his cancer has spread, leaving him with a life expectancy of just six months. With the limited time he has left, he and his best friend and writing partner, Sammy, decide to follow their dreams and finally make an album. Little do they know, they'll soon become a viral music phenomenon. But with time running out, Zach is confronted with the reality that no matter how he spends his time, he is going to hurt the people he loves the most, including Amy, the love of his life. As Zach's health condition begins to worsen, he is left to make difficult decisions about how to spend his time and more importantly with whom. Ultimately, he discovers the best way to say goodbye is with music, and his hit song CLOUDS is born. With an unfiltered, heartbreaking, and beautiful ...",
        "yt_trailer_code": "OWEgUhWU4g4",
        "language": "en",
        "mpa_rating": "PG-13",
        "background_image": "https://yts.mx/assets/images/movies/clouds_2020/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/clouds_2020/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/clouds_2020/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/clouds_2020/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/clouds_2020/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/1BB2950A2DC09D6EDCDBC48FAD312D4E31CF2B05",
            "hash": "1BB2950A2DC09D6EDCDBC48FAD312D4E31CF2B05",
            "quality": "720p",
            "type": "web",
            "seeds": 1192,
            "peers": 739,
            "size": "1.08 GB",
            "size_bytes": 1159641170,
            "date_uploaded": "2020-10-17 07:15:21",
            "date_uploaded_unix": 1602911721
          },
          {
            "url": "https://yts.mx/torrent/download/92502FABB0217E9A7430A4BF36DE853B34BB0F23",
            "hash": "92502FABB0217E9A7430A4BF36DE853B34BB0F23",
            "quality": "1080p",
            "type": "web",
            "seeds": 1164,
            "peers": 522,
            "size": "2.23 GB",
            "size_bytes": 2394444268,
            "date_uploaded": "2020-10-17 09:20:24",
            "date_uploaded_unix": 1602919224
          }
        ],
        "date_uploaded": "2020-10-17 07:15:21",
        "date_uploaded_unix": 1602911721
      },
      {
        "id": 22544,
        "url": "https://yts.mx/movies/the-trial-of-the-chicago-7-2020",
        "imdb_code": "tt1070874",
        "title": "The Trial of the Chicago 7",
        "title_english": "The Trial of the Chicago 7",
        "title_long": "The Trial of the Chicago 7 (2020)",
        "slug": "the-trial-of-the-chicago-7-2020",
        "year": 2020,
        "rating": 8,
        "runtime": 129,
        "genres": [
          "Drama",
          "History",
          "Thriller"
        ],
        "summary": "In Chicago 1968, the Democratic Pary Convention was met with protests from activists like the moderate Students for a Democratic Society led by Tom Hayden and the militant Yippies led by Abbie Hoffman and Jerry Rubin, which led to violent confrontations with the local authorities. As a result, seven of the accused ringleaders are arraigned on charges like Conspiracy by the hostile Nixon administration, including Bobby Seale of the Black Panthers who was not involved in the incident. What follows is an unfair trial presided by the belligerent Judge Hoffman (No relation) and prosecuted by a reluctant but duty-bound Richard Schultz. As their pro bono lawyers face such odds, Hayden and his fellows are frustrated by the Yippies' outrageous antics undermining their defense in defiance of the system even while Seale is denied a chance to defend himself his way. Along the way, the Chicago 7 clash in their political philosophies even as they learn they need each other in this fight.",
        "description_full": "In Chicago 1968, the Democratic Pary Convention was met with protests from activists like the moderate Students for a Democratic Society led by Tom Hayden and the militant Yippies led by Abbie Hoffman and Jerry Rubin, which led to violent confrontations with the local authorities. As a result, seven of the accused ringleaders are arraigned on charges like Conspiracy by the hostile Nixon administration, including Bobby Seale of the Black Panthers who was not involved in the incident. What follows is an unfair trial presided by the belligerent Judge Hoffman (No relation) and prosecuted by a reluctant but duty-bound Richard Schultz. As their pro bono lawyers face such odds, Hayden and his fellows are frustrated by the Yippies' outrageous antics undermining their defense in defiance of the system even while Seale is denied a chance to defend himself his way. Along the way, the Chicago 7 clash in their political philosophies even as they learn they need each other in this fight.",
        "synopsis": "In Chicago 1968, the Democratic Pary Convention was met with protests from activists like the moderate Students for a Democratic Society led by Tom Hayden and the militant Yippies led by Abbie Hoffman and Jerry Rubin, which led to violent confrontations with the local authorities. As a result, seven of the accused ringleaders are arraigned on charges like Conspiracy by the hostile Nixon administration, including Bobby Seale of the Black Panthers who was not involved in the incident. What follows is an unfair trial presided by the belligerent Judge Hoffman (No relation) and prosecuted by a reluctant but duty-bound Richard Schultz. As their pro bono lawyers face such odds, Hayden and his fellows are frustrated by the Yippies' outrageous antics undermining their defense in defiance of the system even while Seale is denied a chance to defend himself his way. Along the way, the Chicago 7 clash in their political philosophies even as they learn they need each other in this fight.",
        "yt_trailer_code": "OAaZIfeQzT0",
        "language": "en",
        "mpa_rating": "R",
        "background_image": "https://yts.mx/assets/images/movies/the_trial_of_the_chicago_7_2020/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/the_trial_of_the_chicago_7_2020/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/the_trial_of_the_chicago_7_2020/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/the_trial_of_the_chicago_7_2020/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/the_trial_of_the_chicago_7_2020/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/ADF4EACBC572E856C20FFF9424F6B2687BA40D04",
            "hash": "ADF4EACBC572E856C20FFF9424F6B2687BA40D04",
            "quality": "720p",
            "type": "web",
            "seeds": 390,
            "peers": 333,
            "size": "1.17 GB",
            "size_bytes": 1256277934,
            "date_uploaded": "2020-10-17 21:13:03",
            "date_uploaded_unix": 1602961983
          },
          {
            "url": "https://yts.mx/torrent/download/DB32D35023A1276435D00916729AF4453A464140",
            "hash": "DB32D35023A1276435D00916729AF4453A464140",
            "quality": "1080p",
            "type": "web",
            "seeds": 518,
            "peers": 546,
            "size": "2.4 GB",
            "size_bytes": 2576980378,
            "date_uploaded": "2020-10-17 23:54:42",
            "date_uploaded_unix": 1602971682
          }
        ],
        "date_uploaded": "2020-10-17 21:13:03",
        "date_uploaded_unix": 1602961983
      },
      {
        "id": 22542,
        "url": "https://yts.mx/movies/kajillionaire-2020",
        "imdb_code": "tt8143990",
        "title": "Kajillionaire",
        "title_english": "Kajillionaire",
        "title_long": "Kajillionaire (2020)",
        "slug": "kajillionaire-2020",
        "year": 2020,
        "rating": 6.5,
        "runtime": 104,
        "genres": [
          "Crime",
          "Drama"
        ],
        "summary": "A woman's life is turned upside down when her criminal parents invite an outsider to join them on a major heist they're planning.",
        "description_full": "A woman's life is turned upside down when her criminal parents invite an outsider to join them on a major heist they're planning.",
        "synopsis": "A woman's life is turned upside down when her criminal parents invite an outsider to join them on a major heist they're planning.",
        "yt_trailer_code": "xiMPCevu8Wk",
        "language": "en",
        "mpa_rating": "R",
        "background_image": "https://yts.mx/assets/images/movies/kajillionaire_2020/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/kajillionaire_2020/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/kajillionaire_2020/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/kajillionaire_2020/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/kajillionaire_2020/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/90B090ED0AF59DCDBBF8514E794D1F526FF9B18F",
            "hash": "90B090ED0AF59DCDBBF8514E794D1F526FF9B18F",
            "quality": "720p",
            "type": "web",
            "seeds": 213,
            "peers": 116,
            "size": "962.07 MB",
            "size_bytes": 1008803512,
            "date_uploaded": "2020-10-17 21:03:28",
            "date_uploaded_unix": 1602961408
          },
          {
            "url": "https://yts.mx/torrent/download/48C54F1F3C8B0A053C04931BC0DC3B18A45293D4",
            "hash": "48C54F1F3C8B0A053C04931BC0DC3B18A45293D4",
            "quality": "1080p",
            "type": "web",
            "seeds": 181,
            "peers": 135,
            "size": "1.93 GB",
            "size_bytes": 2072321720,
            "date_uploaded": "2020-10-17 22:59:19",
            "date_uploaded_unix": 1602968359
          }
        ],
        "date_uploaded": "2020-10-17 21:03:28",
        "date_uploaded_unix": 1602961408
      },
      {
        "id": 22540,
        "url": "https://yts.mx/movies/the-devil-has-a-name-2019",
        "imdb_code": "tt7894510",
        "title": "The Devil Has a Name",
        "title_english": "The Devil Has a Name",
        "title_long": "The Devil Has a Name (2019)",
        "slug": "the-devil-has-a-name-2019",
        "year": 2019,
        "rating": 5.1,
        "runtime": 97,
        "genres": [
          "Drama",
          "Thriller"
        ],
        "summary": "A psychotic oil matriarch leaves the whole industry exposed when she attempts to outfight a bullish farmer whose water has been poisoned.",
        "description_full": "A psychotic oil matriarch leaves the whole industry exposed when she attempts to outfight a bullish farmer whose water has been poisoned.",
        "synopsis": "A psychotic oil matriarch leaves the whole industry exposed when she attempts to outfight a bullish farmer whose water has been poisoned.",
        "yt_trailer_code": "N9nj8v1oyFw",
        "language": "en",
        "mpa_rating": "R",
        "background_image": "https://yts.mx/assets/images/movies/the_devil_has_a_name_2019/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/the_devil_has_a_name_2019/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/the_devil_has_a_name_2019/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/the_devil_has_a_name_2019/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/the_devil_has_a_name_2019/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/8604CBCEC997CCB37882FC75207D43E098ABC60D",
            "hash": "8604CBCEC997CCB37882FC75207D43E098ABC60D",
            "quality": "720p",
            "type": "web",
            "seeds": 68,
            "peers": 42,
            "size": "893.3 MB",
            "size_bytes": 936692941,
            "date_uploaded": "2020-10-18 03:15:16",
            "date_uploaded_unix": 1602983716
          },
          {
            "url": "https://yts.mx/torrent/download/F9436A1804C0A3B18169D96EE950A96B37CB07A1",
            "hash": "F9436A1804C0A3B18169D96EE950A96B37CB07A1",
            "quality": "1080p",
            "type": "web",
            "seeds": 82,
            "peers": 43,
            "size": "1.79 GB",
            "size_bytes": 1921997865,
            "date_uploaded": "2020-10-18 05:12:41",
            "date_uploaded_unix": 1602990761
          }
        ],
        "date_uploaded": "2020-10-18 03:15:16",
        "date_uploaded_unix": 1602983716
      },
      {
        "id": 22539,
        "url": "https://yts.mx/movies/love-and-monsters-2020",
        "imdb_code": "tt2222042",
        "title": "Love and Monsters",
        "title_english": "Love and Monsters",
        "title_long": "Love and Monsters (2020)",
        "slug": "love-and-monsters-2020",
        "year": 2020,
        "rating": 7.2,
        "runtime": 109,
        "genres": [
          "Adventure",
          "Comedy"
        ],
        "summary": "Seven years after the Monsterpocalypse, Joel Dawson (Dylan O'Brien), along with the rest of humanity, has been living underground ever since giant creatures took control of the land. After reconnecting over radio with his high school girlfriend Aimee (Jessica Henwick), who is now 80 miles away at a coastal colony, Joel begins to fall for her again. As Joel realizes that there's nothing left for him underground, he decides against all logic to venture out to Aimee, despite all the dangerous monsters that stand in his way. The fun-filled and action-packed adventure also stars Michael Rooker and Ariana Greenblatt.",
        "description_full": "Seven years after the Monsterpocalypse, Joel Dawson (Dylan O'Brien), along with the rest of humanity, has been living underground ever since giant creatures took control of the land. After reconnecting over radio with his high school girlfriend Aimee (Jessica Henwick), who is now 80 miles away at a coastal colony, Joel begins to fall for her again. As Joel realizes that there's nothing left for him underground, he decides against all logic to venture out to Aimee, despite all the dangerous monsters that stand in his way. The fun-filled and action-packed adventure also stars Michael Rooker and Ariana Greenblatt.",
        "synopsis": "Seven years after the Monsterpocalypse, Joel Dawson (Dylan O'Brien), along with the rest of humanity, has been living underground ever since giant creatures took control of the land. After reconnecting over radio with his high school girlfriend Aimee (Jessica Henwick), who is now 80 miles away at a coastal colony, Joel begins to fall for her again. As Joel realizes that there's nothing left for him underground, he decides against all logic to venture out to Aimee, despite all the dangerous monsters that stand in his way. The fun-filled and action-packed adventure also stars Michael Rooker and Ariana Greenblatt.",
        "yt_trailer_code": "-19tBHrZwOM",
        "language": "en",
        "mpa_rating": "PG-13",
        "background_image": "https://yts.mx/assets/images/movies/love_and_monsters_2020/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/love_and_monsters_2020/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/love_and_monsters_2020/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/love_and_monsters_2020/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/love_and_monsters_2020/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/40BBAEBC0F1AF62640A7D067111C4A6CB2545419",
            "hash": "40BBAEBC0F1AF62640A7D067111C4A6CB2545419",
            "quality": "720p",
            "type": "web",
            "seeds": 1446,
            "peers": 3026,
            "size": "999.41 MB",
            "size_bytes": 1047957340,
            "date_uploaded": "2020-10-18 06:20:12",
            "date_uploaded_unix": 1602994812
          },
          {
            "url": "https://yts.mx/torrent/download/22BBE090578E24C53ED0686FD3B919947563D555",
            "hash": "22BBE090578E24C53ED0686FD3B919947563D555",
            "quality": "1080p",
            "type": "web",
            "seeds": 876,
            "peers": 2044,
            "size": "2.01 GB",
            "size_bytes": 2158221066,
            "date_uploaded": "2020-10-18 08:28:05",
            "date_uploaded_unix": 1603002485
          }
        ],
        "date_uploaded": "2020-10-18 06:20:12",
        "date_uploaded_unix": 1602994812
      },
      {
        "id": 22538,
        "url": "https://yts.mx/movies/the-secrets-we-keep-2020",
        "imdb_code": "tt9252488",
        "title": "The Secrets We Keep",
        "title_english": "The Secrets We Keep",
        "title_long": "The Secrets We Keep (2020)",
        "slug": "the-secrets-we-keep-2020",
        "year": 2020,
        "rating": 5.3,
        "runtime": 97,
        "genres": [
          "Drama",
          "Thriller"
        ],
        "summary": "In post-WWII America, a woman (Rapace), rebuilding her life in the suburbs with her husband (Messina), kidnaps her neighbor (Kinnaman) and seeks vengeance for the heinous war crimes she believes he committed against her. The film is directed by Yuval Adler from a script by Yuval Adler and Ryan Covington.",
        "description_full": "In post-WWII America, a woman (Rapace), rebuilding her life in the suburbs with her husband (Messina), kidnaps her neighbor (Kinnaman) and seeks vengeance for the heinous war crimes she believes he committed against her. The film is directed by Yuval Adler from a script by Yuval Adler and Ryan Covington.",
        "synopsis": "In post-WWII America, a woman (Rapace), rebuilding her life in the suburbs with her husband (Messina), kidnaps her neighbor (Kinnaman) and seeks vengeance for the heinous war crimes she believes he committed against her. The film is directed by Yuval Adler from a script by Yuval Adler and Ryan Covington.",
        "yt_trailer_code": "kGKX5rzRMho",
        "language": "en",
        "mpa_rating": "R",
        "background_image": "https://yts.mx/assets/images/movies/the_secrets_we_keep_2020/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/the_secrets_we_keep_2020/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/the_secrets_we_keep_2020/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/the_secrets_we_keep_2020/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/the_secrets_we_keep_2020/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/7B869EBE1FAE5EF2A792C1D0B82EF296923F9EFF",
            "hash": "7B869EBE1FAE5EF2A792C1D0B82EF296923F9EFF",
            "quality": "720p",
            "type": "web",
            "seeds": 187,
            "peers": 139,
            "size": "902.17 MB",
            "size_bytes": 945993810,
            "date_uploaded": "2020-10-18 00:07:05",
            "date_uploaded_unix": 1602972425
          },
          {
            "url": "https://yts.mx/torrent/download/44AF53F78FB37C1713BDBD91638FB8DCD8BFE6A4",
            "hash": "44AF53F78FB37C1713BDBD91638FB8DCD8BFE6A4",
            "quality": "1080p",
            "type": "web",
            "seeds": 200,
            "peers": 151,
            "size": "1.81 GB",
            "size_bytes": 1943472701,
            "date_uploaded": "2020-10-18 02:11:15",
            "date_uploaded_unix": 1602979875
          }
        ],
        "date_uploaded": "2020-10-18 00:07:05",
        "date_uploaded_unix": 1602972425
      },
      {
        "id": 22537,
        "url": "https://yts.mx/movies/36-husbands-2019",
        "imdb_code": "tt7512492",
        "title": "36 Husbands",
        "title_english": "36 Husbands",
        "title_long": "36 Husbands (2019)",
        "slug": "36-husbands-2019",
        "year": 2019,
        "rating": 4.1,
        "runtime": 83,
        "genres": [
          "Comedy"
        ],
        "summary": "36 Husbands is a mystical, musical, Kung Fu spy comedy starring 3 powerful women - and a bunch of husbands. Krista, top spy and Kung Fu master, has extraordinary powers and she puts them in action on her quest to slow down the steady march towards World War III. Together with her Kung Fu disciples, Gina and Nola, (and Frankie, a spy on-loan from MI6) they fight and love their way across the world leaving a trail of broken hearts and sabotaged plans. All the spies and evil-doers are tuning into the Bright Blue Gorilla TV show. Why do they watch? Is it the music, is it the comedy? Maybe you can figure it out.",
        "description_full": "36 Husbands is a mystical, musical, Kung Fu spy comedy starring 3 powerful women - and a bunch of husbands. Krista, top spy and Kung Fu master, has extraordinary powers and she puts them in action on her quest to slow down the steady march towards World War III. Together with her Kung Fu disciples, Gina and Nola, (and Frankie, a spy on-loan from MI6) they fight and love their way across the world leaving a trail of broken hearts and sabotaged plans. All the spies and evil-doers are tuning into the Bright Blue Gorilla TV show. Why do they watch? Is it the music, is it the comedy? Maybe you can figure it out.",
        "synopsis": "36 Husbands is a mystical, musical, Kung Fu spy comedy starring 3 powerful women - and a bunch of husbands. Krista, top spy and Kung Fu master, has extraordinary powers and she puts them in action on her quest to slow down the steady march towards World War III. Together with her Kung Fu disciples, Gina and Nola, (and Frankie, a spy on-loan from MI6) they fight and love their way across the world leaving a trail of broken hearts and sabotaged plans. All the spies and evil-doers are tuning into the Bright Blue Gorilla TV show. Why do they watch? Is it the music, is it the comedy? Maybe you can figure it out.",
        "yt_trailer_code": "bF2Az7hnxRc",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/36_husbands_2019/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/36_husbands_2019/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/36_husbands_2019/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/36_husbands_2019/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/36_husbands_2019/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/F0FAE6FF8A89648B1FE0D6259269A1BD1AA4C339",
            "hash": "F0FAE6FF8A89648B1FE0D6259269A1BD1AA4C339",
            "quality": "720p",
            "type": "web",
            "seeds": 48,
            "peers": 9,
            "size": "759.09 MB",
            "size_bytes": 795963556,
            "date_uploaded": "2020-10-17 04:37:10",
            "date_uploaded_unix": 1602902230
          },
          {
            "url": "https://yts.mx/torrent/download/BBEDF5C1B45402E109AD91DD202EE408B2E2B7CB",
            "hash": "BBEDF5C1B45402E109AD91DD202EE408B2E2B7CB",
            "quality": "1080p",
            "type": "web",
            "seeds": 46,
            "peers": 27,
            "size": "1.38 GB",
            "size_bytes": 1481763717,
            "date_uploaded": "2020-10-17 06:10:27",
            "date_uploaded_unix": 1602907827
          }
        ],
        "date_uploaded": "2020-10-17 04:37:10",
        "date_uploaded_unix": 1602902230
      },
      {
        "id": 22534,
        "url": "https://yts.mx/movies/2020-billboard-music-awards-2020",
        "imdb_code": "tt11865054",
        "title": "2020 Billboard Music Awards",
        "title_english": "2020 Billboard Music Awards",
        "title_long": "2020 Billboard Music Awards (2020)",
        "slug": "2020-billboard-music-awards-2020",
        "year": 2020,
        "rating": 3.3,
        "runtime": 180,
        "genres": [
          "Music"
        ],
        "summary": "The 2020 BILLBOARD MUSIC AWARDS is a music ceremony that honors artists, albums and songs that dominated to Billboard charts over the past year, and features celebrity presenters and live musical performances.",
        "description_full": "The 2020 BILLBOARD MUSIC AWARDS is a music ceremony that honors artists, albums and songs that dominated to Billboard charts over the past year, and features celebrity presenters and live musical performances.",
        "synopsis": "The 2020 BILLBOARD MUSIC AWARDS is a music ceremony that honors artists, albums and songs that dominated to Billboard charts over the past year, and features celebrity presenters and live musical performances.",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/2020_billboard_music_awards_2020/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/2020_billboard_music_awards_2020/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/2020_billboard_music_awards_2020/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/2020_billboard_music_awards_2020/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/2020_billboard_music_awards_2020/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/6E3AA02E500F3B91512C521EFF514845A042D271",
            "hash": "6E3AA02E500F3B91512C521EFF514845A042D271",
            "quality": "720p",
            "type": "web",
            "seeds": 100,
            "peers": 52,
            "size": "1.11 GB",
            "size_bytes": 1191853425,
            "date_uploaded": "2020-10-17 04:30:42",
            "date_uploaded_unix": 1602901842
          },
          {
            "url": "https://yts.mx/torrent/download/6963D0DF3F4888FF4F7D707F61A924DD7B12C9DB",
            "hash": "6963D0DF3F4888FF4F7D707F61A924DD7B12C9DB",
            "quality": "1080p",
            "type": "web",
            "seeds": 122,
            "peers": 39,
            "size": "2.05 GB",
            "size_bytes": 2201170739,
            "date_uploaded": "2020-10-17 07:43:57",
            "date_uploaded_unix": 1602913437
          }
        ],
        "date_uploaded": "2020-10-17 04:30:42",
        "date_uploaded_unix": 1602901842
      },
      {
        "id": 22520,
        "url": "https://yts.mx/movies/dont-look-back-2020",
        "imdb_code": "tt10418846",
        "title": "Don't Look Back",
        "title_english": "Don't Look Back",
        "title_long": "Don't Look Back (2020)",
        "slug": "dont-look-back-2020",
        "year": 2020,
        "rating": 4.3,
        "runtime": 90,
        "genres": [
          "Horror",
          "Mystery",
          "Thriller"
        ],
        "summary": "When a young woman overcoming her traumatic past is among several witnesses who see a man fatally assaulted and don't intervene, they find themselves targeted by someone, or something, out for revenge.",
        "description_full": "When a young woman overcoming her traumatic past is among several witnesses who see a man fatally assaulted and don't intervene, they find themselves targeted by someone, or something, out for revenge.",
        "synopsis": "When a young woman overcoming her traumatic past is among several witnesses who see a man fatally assaulted and don't intervene, they find themselves targeted by someone, or something, out for revenge.",
        "yt_trailer_code": "HSW4P4U5tCo",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/dont_look_back_2020/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/dont_look_back_2020/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/dont_look_back_2020/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/dont_look_back_2020/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/dont_look_back_2020/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/20D58B9DA258CBF4E510C835FDE8EF7A32B827D6",
            "hash": "20D58B9DA258CBF4E510C835FDE8EF7A32B827D6",
            "quality": "720p",
            "type": "web",
            "seeds": 288,
            "peers": 135,
            "size": "776.24 MB",
            "size_bytes": 813946634,
            "date_uploaded": "2020-10-17 02:01:52",
            "date_uploaded_unix": 1602892912
          },
          {
            "url": "https://yts.mx/torrent/download/212E09EBB082E78A0ECC73F42B56C6CCD3701ED4",
            "hash": "212E09EBB082E78A0ECC73F42B56C6CCD3701ED4",
            "quality": "1080p",
            "type": "web",
            "seeds": 214,
            "peers": 96,
            "size": "1.56 GB",
            "size_bytes": 1675037245,
            "date_uploaded": "2020-10-17 03:47:24",
            "date_uploaded_unix": 1602899244
          }
        ],
        "date_uploaded": "2020-10-17 02:01:52",
        "date_uploaded_unix": 1602892912
      },
      {
        "id": 22448,
        "url": "https://yts.mx/movies/sins-of-the-mother-2010",
        "imdb_code": "tt1518859",
        "title": "Sins of the Mother",
        "title_english": "Sins of the Mother",
        "title_long": "Sins of the Mother (2010)",
        "slug": "sins-of-the-mother-2010",
        "year": 2010,
        "rating": 6.3,
        "runtime": 90,
        "genres": [
          "Drama"
        ],
        "summary": "Shay is a young African-American college student whom is forced to take a year off from school to return to her hometown where she struggles with her anger and insecurity when she's forced to confront her alcoholic mother, Nona, whom is currently in AA and a churchgoer, over her entire childhood of abuse and neglect which Shay is both unwilling and unable to let go of.",
        "description_full": "Shay is a young African-American college student whom is forced to take a year off from school to return to her hometown where she struggles with her anger and insecurity when she's forced to confront her alcoholic mother, Nona, whom is currently in AA and a churchgoer, over her entire childhood of abuse and neglect which Shay is both unwilling and unable to let go of.",
        "synopsis": "Shay is a young African-American college student whom is forced to take a year off from school to return to her hometown where she struggles with her anger and insecurity when she's forced to confront her alcoholic mother, Nona, whom is currently in AA and a churchgoer, over her entire childhood of abuse and neglect which Shay is both unwilling and unable to let go of.",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/sins_of_the_mother_2010/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/sins_of_the_mother_2010/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/sins_of_the_mother_2010/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/sins_of_the_mother_2010/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/sins_of_the_mother_2010/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/AE7227FEAB02DB4C9096BACB0ACDFC77FB2F21A8",
            "hash": "AE7227FEAB02DB4C9096BACB0ACDFC77FB2F21A8",
            "quality": "720p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "814.82 MB",
            "size_bytes": 854400696,
            "date_uploaded": "2020-10-18 12:38:30",
            "date_uploaded_unix": 1603017510
          },
          {
            "url": "https://yts.mx/torrent/download/CA9039411158E78AC1DAC628831C8D8935B04D01",
            "hash": "CA9039411158E78AC1DAC628831C8D8935B04D01",
            "quality": "1080p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "1.48 GB",
            "size_bytes": 1589137900,
            "date_uploaded": "2020-10-18 14:29:45",
            "date_uploaded_unix": 1603024185
          }
        ],
        "date_uploaded": "2020-10-18 12:38:30",
        "date_uploaded_unix": 1603017510
      },
      {
        "id": 22447,
        "url": "https://yts.mx/movies/evil-intent-2019",
        "imdb_code": "tt10255374",
        "title": "Evil Intent",
        "title_english": "Evil Intent",
        "title_long": "Evil Intent (2019)",
        "slug": "evil-intent-2019",
        "year": 2019,
        "rating": 4.2,
        "runtime": 86,
        "genres": [
          "Thriller"
        ],
        "summary": "A young couple Mira (Abbie Cobb) and Todd (Sean Faris) hire a live-in nurse (Lyndon Smith) to be the caregiver for their sick son, only to discover that she is an \"angel of death\" intent on replacing Mira through any means necessary.",
        "description_full": "A young couple Mira (Abbie Cobb) and Todd (Sean Faris) hire a live-in nurse (Lyndon Smith) to be the caregiver for their sick son, only to discover that she is an \"angel of death\" intent on replacing Mira through any means necessary.",
        "synopsis": "A young couple Mira (Abbie Cobb) and Todd (Sean Faris) hire a live-in nurse (Lyndon Smith) to be the caregiver for their sick son, only to discover that she is an \"angel of death\" intent on replacing Mira through any means necessary.",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/evil_intent_2019/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/evil_intent_2019/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/evil_intent_2019/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/evil_intent_2019/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/evil_intent_2019/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/A93EB9DED2591A2D8635EFCE4D76DC0BC8F260DB",
            "hash": "A93EB9DED2591A2D8635EFCE4D76DC0BC8F260DB",
            "quality": "720p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "782.4 MB",
            "size_bytes": 820405862,
            "date_uploaded": "2020-10-18 09:56:02",
            "date_uploaded_unix": 1603007762
          },
          {
            "url": "https://yts.mx/torrent/download/BC6AE563D3B76400A88A568E93F2798D5275336E",
            "hash": "BC6AE563D3B76400A88A568E93F2798D5275336E",
            "quality": "1080p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "1.42 GB",
            "size_bytes": 1524713390,
            "date_uploaded": "2020-10-18 11:39:09",
            "date_uploaded_unix": 1603013949
          }
        ],
        "date_uploaded": "2020-10-18 09:56:02",
        "date_uploaded_unix": 1603007762
      },
      {
        "id": 22441,
        "url": "https://yts.mx/movies/killer-dream-home-2020",
        "imdb_code": "tt11922698",
        "title": "Killer Dream Home",
        "title_english": "Killer Dream Home",
        "title_long": "Killer Dream Home (2020)",
        "slug": "killer-dream-home-2020",
        "year": 2020,
        "rating": 4.7,
        "runtime": 91,
        "genres": [
          "Thriller"
        ],
        "summary": "When happy couple Jules and Josh buy their dream house on a magnificent estate, they recruit beautiful Morgan to help them with the interior design, unaware Morgan has history with the house and will stop at nothing to make it her own.",
        "description_full": "When happy couple Jules and Josh buy their dream house on a magnificent estate, they recruit beautiful Morgan to help them with the interior design, unaware Morgan has history with the house and will stop at nothing to make it her own.",
        "synopsis": "When happy couple Jules and Josh buy their dream house on a magnificent estate, they recruit beautiful Morgan to help them with the interior design, unaware Morgan has history with the house and will stop at nothing to make it her own.",
        "yt_trailer_code": "JrpvQmC_pJ0",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/killer_dream_home_2020/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/killer_dream_home_2020/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/killer_dream_home_2020/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/killer_dream_home_2020/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/killer_dream_home_2020/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/C953377634C461FEC13D6E47AE8393364B8010D8",
            "hash": "C953377634C461FEC13D6E47AE8393364B8010D8",
            "quality": "720p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "839.19 MB",
            "size_bytes": 879954493,
            "date_uploaded": "2020-10-18 11:23:38",
            "date_uploaded_unix": 1603013018
          },
          {
            "url": "https://yts.mx/torrent/download/6962185AD002FC2E09536F74F6151E77C1D31F78",
            "hash": "6962185AD002FC2E09536F74F6151E77C1D31F78",
            "quality": "1080p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "1.52 GB",
            "size_bytes": 1632087572,
            "date_uploaded": "2020-10-18 13:46:57",
            "date_uploaded_unix": 1603021617
          }
        ],
        "date_uploaded": "2020-10-18 11:23:38",
        "date_uploaded_unix": 1603013018
      },
      {
        "id": 22437,
        "url": "https://yts.mx/movies/desperate-trails-1939",
        "imdb_code": "tt0031224",
        "title": "Desperate Trails",
        "title_english": "Desperate Trails",
        "title_long": "Desperate Trails (1939)",
        "slug": "desperate-trails-1939",
        "year": 1939,
        "rating": 6.2,
        "runtime": 60,
        "genres": [
          "Western"
        ],
        "summary": "Following 1939's \"The Phantom Stage\", the last of 12 series westerns made at Universal by Trem Carr and Paul Malvern starring Bob Baker, Universal kicked off a new series of six starring their new series-sign Johnny Mack Brown (who had already starred in three Universal serials with one more to go.) Baker was now odd-man-out at the studio as his contract had been with Trem Carr, and Carr and associate Malvern had moved over to Monogram to begin a series of four \"Tailspin Tommy\" features. Universal, usually late to the party anyway, added Baker and comedian Fuzzy Knight to the first-six Brown films to form a trio angle along the lines of Republic's highly successful \"Three Mesquiteers\" series, but there were no continuing roles in these films---they even killed Baker off in the 2nd film---and Baker's 2nd-lead soon went to 3rd-lead (behind Knight) and then to \"gone\" after the sixth film. When Bob Baker was next seen in a film at Universal, it was as the uncredited bus driver in Abbott ...",
        "description_full": "Following 1939's \"The Phantom Stage\", the last of 12 series westerns made at Universal by Trem Carr and Paul Malvern starring Bob Baker, Universal kicked off a new series of six starring their new series-sign Johnny Mack Brown (who had already starred in three Universal serials with one more to go.) Baker was now odd-man-out at the studio as his contract had been with Trem Carr, and Carr and associate Malvern had moved over to Monogram to begin a series of four \"Tailspin Tommy\" features. Universal, usually late to the party anyway, added Baker and comedian Fuzzy Knight to the first-six Brown films to form a trio angle along the lines of Republic's highly successful \"Three Mesquiteers\" series, but there were no continuing roles in these films---they even killed Baker off in the 2nd film---and Baker's 2nd-lead soon went to 3rd-lead (behind Knight) and then to \"gone\" after the sixth film. When Bob Baker was next seen in a film at Universal, it was as the uncredited bus driver in Abbott ...",
        "synopsis": "Following 1939's \"The Phantom Stage\", the last of 12 series westerns made at Universal by Trem Carr and Paul Malvern starring Bob Baker, Universal kicked off a new series of six starring their new series-sign Johnny Mack Brown (who had already starred in three Universal serials with one more to go.) Baker was now odd-man-out at the studio as his contract had been with Trem Carr, and Carr and associate Malvern had moved over to Monogram to begin a series of four \"Tailspin Tommy\" features. Universal, usually late to the party anyway, added Baker and comedian Fuzzy Knight to the first-six Brown films to form a trio angle along the lines of Republic's highly successful \"Three Mesquiteers\" series, but there were no continuing roles in these films---they even killed Baker off in the 2nd film---and Baker's 2nd-lead soon went to 3rd-lead (behind Knight) and then to \"gone\" after the sixth film. When Bob Baker was next seen in a film at Universal, it was as the uncredited bus driver in Abbott ...",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/desperate_trails_1939/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/desperate_trails_1939/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/desperate_trails_1939/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/desperate_trails_1939/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/desperate_trails_1939/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/871B5D8EF8E3A21E082D837D8E10C4DAF0B24F21",
            "hash": "871B5D8EF8E3A21E082D837D8E10C4DAF0B24F21",
            "quality": "720p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "539.72 MB",
            "size_bytes": 565937439,
            "date_uploaded": "2020-10-18 07:54:02",
            "date_uploaded_unix": 1603000442
          },
          {
            "url": "https://yts.mx/torrent/download/624F42F2AB9106F5E5C44B86C7EBAD6F88340DB3",
            "hash": "624F42F2AB9106F5E5C44B86C7EBAD6F88340DB3",
            "quality": "1080p",
            "type": "web",
            "seeds": 39,
            "peers": 27,
            "size": "1001.97 MB",
            "size_bytes": 1050641695,
            "date_uploaded": "2020-10-18 09:00:17",
            "date_uploaded_unix": 1603004417
          }
        ],
        "date_uploaded": "2020-10-18 07:54:02",
        "date_uploaded_unix": 1603000442
      },
      {
        "id": 22433,
        "url": "https://yts.mx/movies/the-duellists-1977",
        "imdb_code": "tt0075968",
        "title": "The Duellists",
        "title_english": "The Duellists",
        "title_long": "The Duellists (1977)",
        "slug": "the-duellists-1977",
        "year": 1977,
        "rating": 7.4,
        "runtime": 100,
        "genres": [
          "Drama",
          "War"
        ],
        "summary": "Set during the grand, sweeping Napoleonic age, an officer in the French army insults another officer and sets off a life-long enmity. The two officers, D'Hubert and Feraud, cross swords time and time again in an attempt to achieve justice and preserve their honor.",
        "description_full": "Set during the grand, sweeping Napoleonic age, an officer in the French army insults another officer and sets off a life-long enmity. The two officers, D'Hubert and Feraud, cross swords time and time again in an attempt to achieve justice and preserve their honor.",
        "synopsis": "Set during the grand, sweeping Napoleonic age, an officer in the French army insults another officer and sets off a life-long enmity. The two officers, D'Hubert and Feraud, cross swords time and time again in an attempt to achieve justice and preserve their honor.",
        "yt_trailer_code": "ChuhXe0G5lY",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/the_duellists_1977/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/the_duellists_1977/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/the_duellists_1977/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/the_duellists_1977/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/the_duellists_1977/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/D11CF2E7CA4092BBFF95D047C29EDB51C3782816",
            "hash": "D11CF2E7CA4092BBFF95D047C29EDB51C3782816",
            "quality": "720p",
            "type": "bluray",
            "seeds": 90,
            "peers": 55,
            "size": "924.06 MB",
            "size_bytes": 968947139,
            "date_uploaded": "2020-10-18 05:01:58",
            "date_uploaded_unix": 1602990118
          },
          {
            "url": "https://yts.mx/torrent/download/F213F4AF7E520EBF5635C4F4C25002564D2E79FB",
            "hash": "F213F4AF7E520EBF5635C4F4C25002564D2E79FB",
            "quality": "1080p",
            "type": "bluray",
            "seeds": 0,
            "peers": 0,
            "size": "1.85 GB",
            "size_bytes": 1986422374,
            "date_uploaded": "2020-10-18 07:05:31",
            "date_uploaded_unix": 1602997531
          }
        ],
        "date_uploaded": "2020-10-18 05:01:58",
        "date_uploaded_unix": 1602990118
      },
      {
        "id": 22427,
        "url": "https://yts.mx/movies/custody-2016",
        "imdb_code": "tt4575930",
        "title": "Custody",
        "title_english": "Custody",
        "title_long": "Custody (2016)",
        "slug": "custody-2016",
        "year": 2016,
        "rating": 6.4,
        "runtime": 104,
        "genres": [
          "Drama"
        ],
        "summary": "The lives of three women are unexpectedly changed when they cross paths at a New York Family Court.",
        "description_full": "The lives of three women are unexpectedly changed when they cross paths at a New York Family Court.",
        "synopsis": "The lives of three women are unexpectedly changed when they cross paths at a New York Family Court.",
        "yt_trailer_code": "IbtLwewhtCA",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/custody_2016/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/custody_2016/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/custody_2016/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/custody_2016/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/custody_2016/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/71E198ABC9A915EB4AC003A0B95DE85E5278AE40",
            "hash": "71E198ABC9A915EB4AC003A0B95DE85E5278AE40",
            "quality": "720p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "908.53 MB",
            "size_bytes": 952662753,
            "date_uploaded": "2020-10-18 07:29:36",
            "date_uploaded_unix": 1602998976
          },
          {
            "url": "https://yts.mx/torrent/download/4DC29C4B7BC1950EAF1ED449AAFAD3108D250CED",
            "hash": "4DC29C4B7BC1950EAF1ED449AAFAD3108D250CED",
            "quality": "1080p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "1.65 GB",
            "size_bytes": 1771674010,
            "date_uploaded": "2020-10-18 10:10:06",
            "date_uploaded_unix": 1603008606
          }
        ],
        "date_uploaded": "2020-10-18 07:29:36",
        "date_uploaded_unix": 1602998976
      },
      {
        "id": 22425,
        "url": "https://yts.mx/movies/ce-qui-me-meut-1989",
        "imdb_code": "tt0276847",
        "title": "Ce qui me meut",
        "title_english": "Ce qui me meut",
        "title_long": "Ce qui me meut (1989)",
        "slug": "ce-qui-me-meut-1989",
        "year": 1989,
        "rating": 6.3,
        "runtime": 24,
        "summary": "The life of Etienne-Jules Marey, the 19th century pioneer of photography and cinema, famous for studying animal and human locomotion.",
        "description_full": "The life of Etienne-Jules Marey, the 19th century pioneer of photography and cinema, famous for studying animal and human locomotion.",
        "synopsis": "The life of Etienne-Jules Marey, the 19th century pioneer of photography and cinema, famous for studying animal and human locomotion.",
        "yt_trailer_code": "",
        "language": "fr",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/ce_qui_me_meut_1989/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/ce_qui_me_meut_1989/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/ce_qui_me_meut_1989/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/ce_qui_me_meut_1989/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/ce_qui_me_meut_1989/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/E1E992C5CFCAAD0D8CDE52712D65C05F830A4291",
            "hash": "E1E992C5CFCAAD0D8CDE52712D65C05F830A4291",
            "quality": "720p",
            "type": "bluray",
            "seeds": 0,
            "peers": 0,
            "size": "204.47 MB",
            "size_bytes": 214402335,
            "date_uploaded": "2020-10-18 11:51:23",
            "date_uploaded_unix": 1603014683
          },
          {
            "url": "https://yts.mx/torrent/download/AE0BEE2C5B1E1C36A67F0D6B6F2544D7FB83C2CF",
            "hash": "AE0BEE2C5B1E1C36A67F0D6B6F2544D7FB83C2CF",
            "quality": "1080p",
            "type": "bluray",
            "seeds": 0,
            "peers": 0,
            "size": "379.51 MB",
            "size_bytes": 397945078,
            "date_uploaded": "2020-10-18 12:24:14",
            "date_uploaded_unix": 1603016654
          }
        ],
        "date_uploaded": "2020-10-18 11:51:23",
        "date_uploaded_unix": 1603014683
      },
      {
        "id": 22424,
        "url": "https://yts.mx/movies/black-test-car-1962",
        "imdb_code": "tt0056158",
        "title": "Black Test Car",
        "title_english": "Black Test Car",
        "title_long": "Black Test Car (1962)",
        "slug": "black-test-car-1962",
        "year": 1962,
        "rating": 7,
        "runtime": 95,
        "genres": [
          "Crime",
          "Drama",
          "Mystery",
          "Thriller"
        ],
        "summary": "Two car manufacturers spy on each other to try to find out details and prices of a new sports car each is about to launch.",
        "description_full": "Two car manufacturers spy on each other to try to find out details and prices of a new sports car each is about to launch.",
        "synopsis": "Two car manufacturers spy on each other to try to find out details and prices of a new sports car each is about to launch.",
        "yt_trailer_code": "",
        "language": "ja",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/black_test_car_1962/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/black_test_car_1962/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/black_test_car_1962/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/black_test_car_1962/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/black_test_car_1962/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/488EC5CCCD10DA553C68794B7BDABFB95C474786",
            "hash": "488EC5CCCD10DA553C68794B7BDABFB95C474786",
            "quality": "720p",
            "type": "bluray",
            "seeds": 35,
            "peers": 13,
            "size": "867.84 MB",
            "size_bytes": 909996196,
            "date_uploaded": "2020-10-18 02:07:20",
            "date_uploaded_unix": 1602979640
          },
          {
            "url": "https://yts.mx/torrent/download/8B9C0B867E9B29D8D90D8EF48869D3AA0349F473",
            "hash": "8B9C0B867E9B29D8D90D8EF48869D3AA0349F473",
            "quality": "1080p",
            "type": "bluray",
            "seeds": 46,
            "peers": 23,
            "size": "1.57 GB",
            "size_bytes": 1685774664,
            "date_uploaded": "2020-10-18 03:57:00",
            "date_uploaded_unix": 1602986220
          }
        ],
        "date_uploaded": "2020-10-18 02:07:20",
        "date_uploaded_unix": 1602979640
      },
      {
        "id": 22422,
        "url": "https://yts.mx/movies/ambush-at-tomahawk-gap-1953",
        "imdb_code": "tt0045502",
        "title": "Ambush at Tomahawk Gap",
        "title_english": "Ambush at Tomahawk Gap",
        "title_long": "Ambush at Tomahawk Gap (1953)",
        "slug": "ambush-at-tomahawk-gap-1953",
        "year": 1953,
        "rating": 5.9,
        "runtime": 73,
        "genres": [
          "Action",
          "Romance",
          "Western"
        ],
        "summary": "Hodiak, Brian, Derek and Teal have just been released from prison. They return to Tomahawk Gap, now a ghost town, to retrieve the money that they stole and was buried by a partner somewhere in the town. While hunting, the Indians attack, and a life and death battle ensues.",
        "description_full": "Hodiak, Brian, Derek and Teal have just been released from prison. They return to Tomahawk Gap, now a ghost town, to retrieve the money that they stole and was buried by a partner somewhere in the town. While hunting, the Indians attack, and a life and death battle ensues.",
        "synopsis": "Hodiak, Brian, Derek and Teal have just been released from prison. They return to Tomahawk Gap, now a ghost town, to retrieve the money that they stole and was buried by a partner somewhere in the town. While hunting, the Indians attack, and a life and death battle ensues.",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/ambush_at_tomahawk_gap_1953/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/ambush_at_tomahawk_gap_1953/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/ambush_at_tomahawk_gap_1953/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/ambush_at_tomahawk_gap_1953/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/ambush_at_tomahawk_gap_1953/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/B8785D94623421B9C269024D244839DFB4DB8F28",
            "hash": "B8785D94623421B9C269024D244839DFB4DB8F28",
            "quality": "720p",
            "type": "web",
            "seeds": 52,
            "peers": 27,
            "size": "671.63 MB",
            "size_bytes": 704255099,
            "date_uploaded": "2020-10-18 04:27:04",
            "date_uploaded_unix": 1602988024
          },
          {
            "url": "https://yts.mx/torrent/download/687AF13C9EEC938FD16470DA66B291CCD45002FA",
            "hash": "687AF13C9EEC938FD16470DA66B291CCD45002FA",
            "quality": "1080p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "1.22 GB",
            "size_bytes": 1309965025,
            "date_uploaded": "2020-10-18 06:05:46",
            "date_uploaded_unix": 1602993946
          }
        ],
        "date_uploaded": "2020-10-18 04:27:04",
        "date_uploaded_unix": 1602988024
      },
      {
        "id": 22423,
        "url": "https://yts.mx/movies/and-baby-will-fall-2011",
        "imdb_code": "tt1815588",
        "title": "And Baby Will Fall",
        "title_english": "And Baby Will Fall",
        "title_long": "And Baby Will Fall (2011)",
        "slug": "and-baby-will-fall-2011",
        "year": 2011,
        "rating": 5.6,
        "runtime": 0,
        "genres": [
          "Drama",
          "Thriller"
        ],
        "summary": "Model citizen David Rose runs a garden center and is a devoted house-father. Like his wife Ivy, who suffered two stillbirths, their new neighbor Melinda is near to giving birth. Just after David showed her around in the Rose home, Melinda goes missing. Although no corpse is found, just circumstantial evidence more likely to be planted then stupidly left behind, police detective Blanchard treats David as his sole suspect, soon arrested, even after nosy neighbor Bindel is knocked down while David is in jail. School buddy Theo does his best to counsel the couple, yet Ivy doubts her husband's innocence just because of indications he may have had an affair with Melinda since high-school, and starts snooping with her best friend Jody. The worst crime is still being hatched.",
        "description_full": "Model citizen David Rose runs a garden center and is a devoted house-father. Like his wife Ivy, who suffered two stillbirths, their new neighbor Melinda is near to giving birth. Just after David showed her around in the Rose home, Melinda goes missing. Although no corpse is found, just circumstantial evidence more likely to be planted then stupidly left behind, police detective Blanchard treats David as his sole suspect, soon arrested, even after nosy neighbor Bindel is knocked down while David is in jail. School buddy Theo does his best to counsel the couple, yet Ivy doubts her husband's innocence just because of indications he may have had an affair with Melinda since high-school, and starts snooping with her best friend Jody. The worst crime is still being hatched.",
        "synopsis": "Model citizen David Rose runs a garden center and is a devoted house-father. Like his wife Ivy, who suffered two stillbirths, their new neighbor Melinda is near to giving birth. Just after David showed her around in the Rose home, Melinda goes missing. Although no corpse is found, just circumstantial evidence more likely to be planted then stupidly left behind, police detective Blanchard treats David as his sole suspect, soon arrested, even after nosy neighbor Bindel is knocked down while David is in jail. School buddy Theo does his best to counsel the couple, yet Ivy doubts her husband's innocence just because of indications he may have had an affair with Melinda since high-school, and starts snooping with her best friend Jody. The worst crime is still being hatched.",
        "yt_trailer_code": "",
        "language": "en",
        "mpa_rating": "",
        "background_image": "https://yts.mx/assets/images/movies/and_baby_will_fall_2011/background.jpg",
        "background_image_original": "https://yts.mx/assets/images/movies/and_baby_will_fall_2011/background.jpg",
        "small_cover_image": "https://yts.mx/assets/images/movies/and_baby_will_fall_2011/small-cover.jpg",
        "medium_cover_image": "https://yts.mx/assets/images/movies/and_baby_will_fall_2011/medium-cover.jpg",
        "large_cover_image": "https://yts.mx/assets/images/movies/and_baby_will_fall_2011/large-cover.jpg",
        "state": "ok",
        "torrents": [
          {
            "url": "https://yts.mx/torrent/download/59B9CF2B5E9385C4EE2513BEF84F56AC818C5F08",
            "hash": "59B9CF2B5E9385C4EE2513BEF84F56AC818C5F08",
            "quality": "720p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "800.82 MB",
            "size_bytes": 839720632,
            "date_uploaded": "2020-10-18 12:52:14",
            "date_uploaded_unix": 1603018334
          },
          {
            "url": "https://yts.mx/torrent/download/C0D2F79A0BAF3A6EF9489571B50195CFFB3681A6",
            "hash": "C0D2F79A0BAF3A6EF9489571B50195CFFB3681A6",
            "quality": "1080p",
            "type": "web",
            "seeds": 0,
            "peers": 0,
            "size": "1.45 GB",
            "size_bytes": 1556925645,
            "date_uploaded": "2020-10-18 15:00:20",
            "date_uploaded_unix": 1603026020
          }
        ],
        "date_uploaded": "2020-10-18 12:52:14",
        "date_uploaded_unix": 1603018334
      }
    ]
    return categories;
  }

}

export default new API();
